# Generated by Django 4.0.4 on 2022-04-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convert", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="converttask",
            name="error_msg",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
